---
- name: "Build a container with ansible"
  hosts: localhoast
  connection: local
  tasks:
    - name: stop current running container
      command: docker stop web-container
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm web-container
      ignore_errors: yes

    - name: remove web-image
      command: docker rmi web
      ignore_errors: yes

    - name: build docker images using the Dockerfile
      command: docker build -t web .

    - name: Push image to dockerhub
      command: docker push web

    - name: run container
      command: docker run -d -p 5000:80 --name web-conatiner web

